packages:
  - 'packages/*'
  - 'examples/*'

engineStrict: true

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*types*'

allowBuilds:
  esbuild: true
  msw: true
  sharp: true

minimumReleaseAgeExclude:
  - '@aep-foundation/core@0.5.1'
  - '@aep-foundation/express@0.2.3'
  - '@aep-foundation/service@0.3.2'
